Задание module5-task1
htmlacademy-adaptive/174509-sedona-20 pull request #8
Opened 2020-08-26 15:30 UTC by IKolyada

2020-08-26 16:39 UTC, Shramkoweb requested changes

2020-08-26 16:39 UTC, Shramkoweb commented on source/img/icon-burger.svg
> +<svg fill="#81B3D2" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="76.166px" height="68.959px" viewBox="0 0 76.166 68.
А это не сломает потом активные состояния ? Все ок?

2020-08-26 16:39 UTC, Shramkoweb commented on source/js/menu.js
> +var closeMenu = navMenu.querySelector('.main-nav__close');
Сделать 1 кнопку )

2020-08-26 16:39 UTC, Shramkoweb commented on source/sass/base.scss
> +}
Что они тут делают и что это за классы?

2020-08-26 16:39 UTC, Shramkoweb commented on source/sass/card.scss
> +  }
Они идентичные, можно через запятую не дублировать код

2020-08-26 16:39 UTC, Shramkoweb commented on source/sass/fieldset.scss
> +  outline: none;
Ты спрятала аутлайн, а кастомный добавила вместо него?

2020-08-26 16:39 UTC, Shramkoweb commented on source/sass/legend.scss
> +    }
Код повторяется

2020-08-26 16:56 UTC, IKolyada commented on source/sass/base.scss
> +}
1.в макете есть текст, где стоит перенос фразы только начиная с планшетов
.break - это класс для <br> чтобы текст был в одну строку на телефоне, а на планшете срабатывал перенос

2. на макете в телефонах и планшетах в лейбле для поля телефона написано "контактный телефон", а на макете для десктопа просто "телефон"
я сделала <span class="hide">Контактный </span>телефон*:  
чтобы его не было на десктопе

2020-08-27 11:50 UTC, IKolyada commented on source/img/icon-burger.svg
> +<svg fill="#81B3D2" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="76.166px" height="68.959px" viewBox="0 0 76.166 68.
у этих иконок нет активный состояний

2020-08-27 15:59 UTC, Shramkoweb commented on source/sass/title.scss
> +.title_br {
Я бы придумал что-то более подходящее.
Например title_wrap

2020-08-27 15:59 UTC, Shramkoweb approved these changes

2020-08-27 15:59 UTC, merged

2020-08-27 16:02 UTC, IKolyada commented on source/sass/title.scss
> +.title_br {
ok)